### ISSUE TITLE
Missing feature for parachain runtime?

### ISSUE THREAD

**Issue by ntn-x2** [paritytech/cumulus#2230]
After upgrading from 0.9.37 to 9.9.38, our parachain runtimes compiled only with the benchmarking flag have started failing.

```
cargo check -p peregrine-runtime --features runtime-benchmarks

⚡ Found 3 strongly connected components which includes at least one cycle each
cycle(001) ∈ α: DisputeCoordinator ~~{"DisputeDistributionMessage"}~~> DisputeDistribution ~~{"DisputeCoordinatorMessage"}~~>  *
cycle(002) ∈ β: CandidateBacking ~~{"CollatorProtocolMessage"}~~> CollatorProtocol ~~{"CandidateBackingMessage"}~~>  *
cycle(003) ∈ γ: NetworkBridgeRx ~~{"GossipSupportMessage"}~~> GossipSupport ~~{"NetworkBridgeRxMessage"}~~>  *
    Checking polkadot-runtime v0.9.38 (https://github.com/paritytech/polkadot?branch=release-v0.9.38#72309a2b)
error[E0046]: not all trait items implemented, missing: `ReachableDest`
   --> /home/antonio/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/72309a2/runtime/polkadot/src/xcm_config.rs:366:1
    |
366 | impl pallet_xcm::Config for Runtime {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `ReachableDest` in implementation
    |
    = help: implement the missing item: `type ReachableDest = Type;`

For more information about this error, try `rustc --explain E0046`.
error: could not compile `polkadot-runtime` due to previous error
```

The error is generated in the `polkadot-runtime` crate, which I am not sure how deep inside the dependency tree is, and it seems an issue with the `runtime-benchmarks` flag not being properly set by one of the crates that our runtime depends on.

On a related note, I was not even able to compile the statemine runtime on its own with just the `runtime-benchmarks` feature either, but with a different error regarding the new `try_success_origin` syntax, which gives me the hint that not all feature combinations are working for the cumulus repo.

EDIT: [this](https://github.com/KILTprotocol/kilt-node/pull/480) is the PR to update from 0.9.37 to 0.9.38. If our parachain runtimes are compiled with `cargo build -p peregrine-runtime --features runtime-benchmarks`, then we have the compilation issue.

EDIT 2: compiling the whole `kilt-parachain` node with just the `runtime-benchmarks` feature works, so something in the client side is causing the feature from being correctly enabled by the dependencies.

**Comment by ntn-x2** [comment]
If I pull the latest version of the `polkadot-v0.9.38` branch and run `cargo check --features runtime-benchmarks` inside the parachain template runtime, I still get the following error:

```
error[E0046]: not all trait items implemented, missing: `try_successful_origin`
    --> /home/antonio/.cargo/git/checkouts/substrate-7e08433d4c370a21/18bb7c7/frame/collective/src/lib.rs:1109:1
     |
1109 | / impl<
1110 | |         O: Into<Result<RawOrigin<AccountId, I>, O>> + From<RawOrigin<AccountId, I>>,
1111 | |         I,
1112 | |         AccountId: Decode,
1113 | |     > EnsureOrigin<O> for EnsureMember<AccountId, I>
     | |____________________________________________________^ missing `try_successful_origin` in implementation
     |
     = help: implement the missing item: `fn try_successful_origin() -> Result<OuterOrigin, ()> { todo!() }`

error[E0046]: not all trait items implemented, missing: `try_successful_origin`
    --> /home/antonio/.cargo/git/checkouts/substrate-7e08433d4c370a21/18bb7c7/frame/collective/src/lib.rs:1133:1
     |
1133 | / impl<
1134 | |         O: Into<Result<RawOrigin<AccountId, I>, O>> + From<RawOrigin<AccountId, I>>,
1135 | |         AccountId,
1136 | |         I,
1137 | |         const N: u32,
1138 | |     > EnsureOrigin<O> for EnsureMembers<AccountId, I, N>
     | |________________________________________________________^ missing `try_successful_origin` in implementation
     |
     = help: implement the missing item: `fn try_successful_origin() -> Result<OuterOrigin, ()> { todo!() }`

error[E0046]: not all trait items implemented, missing: `try_successful_origin`
    --> /home/antonio/.cargo/git/checkouts/substrate-7e08433d4c370a21/18bb7c7/frame/collective/src/lib.rs:1157:1
     |
1157 | / impl<
1158 | |         O: Into<Result<RawOrigin<AccountId, I>, O>> + From<RawOrigin<AccountId, I>>,
1159 | |         AccountId,
1160 | |         I,
1161 | |         const N: u32,
1162 | |         const D: u32,
1163 | |     > EnsureOrigin<O> for EnsureProportionMoreThan<AccountId, I, N, D>
     | |______________________________________________________________________^ missing `try_successful_origin` in implementation
     |
     = help: implement the missing item: `fn try_successful_origin() -> Result<OuterOrigin, ()> { todo!() }`

error[E0046]: not all trait items implemented, missing: `try_successful_origin`
    --> /home/antonio/.cargo/git/checkouts/substrate-7e08433d4c370a21/18bb7c7/frame/collective/src/lib.rs:1182:1
     |
1182 | / impl<
1183 | |         O: Into<Result<RawOrigin<AccountId, I>, O>> + From<RawOrigin<AccountId, I>>,
1184 | |         AccountId,
1185 | |         I,
1186 | |         const N: u32,
1187 | |         const D: u32,
1188 | |     > EnsureOrigin<O> for EnsureProportionAtLeast<AccountId, I, N, D>
     | |_____________________________________________________________________^ missing `try_successful_origin` in implementation
     |
     = help: implement the missing item: `fn try_successful_origin() -> Result<OuterOrigin, ()> { todo!() }`

For more information about this error, try `rustc --explain E0046`.
error: could not compile `pallet-collective` due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by ggwpez** [comment]
Yea I looked into it locally but could not pinpoint where a feature is missing or erroneously being propagated…  
But it does reproduce.

**Comment by bkontur** [comment]
hmm, I have the similiar/same problem here: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2490428
I tried [this}(https://github.com/paritytech/cumulus/pull/2167/commits/24d02744811048fcd56e0aa453f9cf4c611f609c) but didnt help

**Comment by ntn-x2** [comment]
It is currently breaking our runtimes compilation whenever the feature is enabled. The node compilation is fine, probably because the default `std` somehow fixes the issue.

**Comment by bkchr** [comment]
https://github.com/paritytech/cumulus/commit/6d1ac27a0a4b47fc6e4cf6fc5e6ed500ec26cd15 cherry picked this pr to fix it. For me it works, can you test it @ntn-x2?

**Comment by ntn-x2** [comment]
@bkchr cool, the fix works when compiling the template runtime with the benchmark feature only. Could this be backported to at least the 0.9.38 branch? Or will it be only included in the 0.9.39?

**Comment by bkchr** [comment]
I already backported it to the 0.9.38 branch. (this is the commit I linked above)

**Comment by bkchr** [comment]
Can we close this @ntn-x2?

**Comment by ntn-x2** [comment]
Yes, issue seems fixed also for our runtime compilation. Thanks for the quick fix!
