### ISSUE TITLE
v0.9.13 doesn't compile with latest Substrate v0.9.13

### ISSUE THREAD

**Issue by xlc** [paritytech/cumulus#862]
on `polkadot-v0.9.13` branch, run `cargo update -p sp-io ` and `cargo check` will fail

```
error[E0423]: expected function, tuple struct or tuple variant, found struct variant `pallet_balances::Event::Deposit`
   --> polkadot-parachains/parachains-common/src/impls.rs:50:44
    |
50  |           <frame_system::Pallet<R>>::deposit_event(pallet_balances::Event::Deposit(
    |  __________________________________________________^
51  | |             staking_pot,
52  | |             numeric_amount,
53  | |         ));
    | |_________^ help: use struct literal syntax instead: `pallet_balances::Event::Deposit { /* fields */ }`
    |
   ::: /Users/xiliangchen/.cargo/git/checkouts/substrate-7e08433d4c370a21/fcc54a7/frame/balances/src/lib.rs:462:9
    |
462 |           Deposit { who: T::AccountId, amount: T::Balance },
    |           ------- `pallet_balances::Event::Deposit` defined here

For more information about this error, try `rustc --explain E0423`.
error: could not compile `parachains-common` due to previous error
```

**Comment by bkchr** [comment]
Fixed.
